### PR TITLE
Update FSH Syntax highlighting

### PR DESCRIPTION
**Pull request by jafeltra**
This PR updates the FSH syntax highlighting to more closely match what is in the VS Code extension. This adds a few new updates to the highlighting:

- Includes the `+` as a symbol (this is actually not supported in the VS Code extension, but I'll include it there as well)
- New keywords for Logical and Resource
- Highlights numbers
- Highlights quoted codes (`#"code with spaces"`)
- Highlight single quoted ucum units (`'lb'`)
- Highlight Reference and Canonical keyword. In the VS Code extension, we used more than just a regular expression to match the start and end parentheses without highlight the characters inside them. I'm not sure how to do that using the simple mode.

There are still three meaningful shortcomings:

- The simple mode we use for defining a language syntax in CodeMirror still does not support the lookbehind in regular expressions, so there are a few regular expressions that do not include that. This is the reason that `coding.system` will highlight system incorrectly.
- There are a few regular expressions that check that there is whitespace following the pattern. I haven't included this because CodeMirror doesn't seem to register a new line as white space, so I thought it would be better to have the value highlighting a few extra times rather than miss a few.
- The `\b` word boundary flag doesn't seem to be working as expected, which is what is leading to the `discriminator[0]` highlighting the `or`. I would have expected the `\b` on either side of the regular expression for the keywords to not match in that case.

These shortcomings might now be occurring often enough that we might want to consider expanding the language mode beyond the simple mode we are currently using. However, I thought it was better to get these fixes in first before embarking on that refactor.

This addresses some of the concerns in #54 but not all of them.

### CODE REVIEW

**Review by cmoesel — APPROVED** [review]
I've tried this and it works as advertised.  I agree that the behavior is odd (related to the `or` issue).  I tried a few other regular expression variations (like using `(^|\s)` in place of the first `\b` and `(\s|$)` in place of the last `\b` -- but those just exhibited the same problems.

Still, this PR leaves things in a better state than they were.  So I am approving.

**Review by cmoesel — CHANGES_REQUESTED** [review]
Revoking my approval because I just realized that when I ran `npm install`, I ended up w/ a different `package-lock.json` than what is checked in here.  Can you check on that?

**Comment by jafeltra** [comment]
@cmoesel I'm not sure why `package-lock.json` was out of date since this PR didn't change any packages, but I re-ran `npm install` and added the latest changes to `package-lock.json` here. I also merged in master, so this should be set again.

**Review by julianxcarter — APPROVED** [review]

**Review by cmoesel — APPROVED** [review]
Thanks, @jafeltra!

**Pull request merged**
