### PR TITLE
Add variations on start and build scripts for Windows systems

### PR DESCRIPTION
**Pull request by mint-thompson**
These scripts set an environment variable before invoking react-app-rewired. The syntax for doing this is different on Windows systems. Two new scripts are defined to make these actions available to Windows users.

### CODE REVIEW

**Review by jafeltra — DISMISSED** [review]

**Comment by jafeltra** [comment]
I tried using `start:win` on my Mac and it does not work. So I guess we can discuss whether we want to add cross-env and use that in one script or keep both.

**Comment by cmoesel** [comment]
I say let's use [cross-env](https://www.npmjs.com/package/cross-env). It's designed exactly for this purpose and is super easy to use.

**Comment by cmoesel** [comment]
I had some time, so I switched this over to using `cross-env`. It still works on Mac. At this point, we can only assume it works on Windows (if there is truth in advertising).

**Review by cmoesel — APPROVED** [review]
Wow, Mint and Chris. This looks great!

**Review by jafeltra — APPROVED** [review]

**Pull request merged**
