### PR TITLE
Minor updates to prepare for GoFSH release

### PR DESCRIPTION
**Pull request by jafeltra**
This PR makes a few minor changes to prepare for the release of the GoFSH feature in FSH Online:

- Updates SUSHI to v1.3.2
- Updates GoFSH to v1.1.0
- Removes the mention of an "alpha version" from the README
- Merges master into the branch again, which should now allow `gofsh` to merge into `master` cleanly.

### CODE REVIEW

**Comment by jafeltra** [comment]
I updated all vulnerabilities that I could fix automatically. As you can see I also tried to update `react-scripts` which was a major version bump, but something in the tests broke relating to the editor, so I didn't feel comfortable merging that into this large feature branch/release, so I revered it. This should be set again!

**Review by cmoesel — APPROVED** [review]
TOTALLY RAD!

**Review by ngfreiter — APPROVED** [review]
👍 🎉

**Comment by cmoesel** [comment]
I know I already approved this, but @jafeltra -- what would you think of bumping the version in `package.json` from `0.1.0` to `1.0.0`?  I know it doesn't really do anything, but it would still help to represent that shift from alpha to not-alpha.

**Comment by jafeltra** [comment]
@cmoesel I feel great about it! 47a1285

**Review by cmoesel — APPROVED** [review]
TOTALLY RADDER!

**Pull request merged**
