### PR TITLE
Add Definition and Delete Definition buttons

### PR DESCRIPTION
**Pull request by jafeltra**
This PR adds a "Add definition" button to the file tree on the RHS. This lets you add a blank definition and open a blank editor to type the definition into. As you add text to the definition, the definition should be sorted into the correct category in the file tree and the id should populate.

This also adds a delete button so you can remove a full definition. Deleting the definition will remove it from the file tree and will remove it from the set of definitions that GoFSH is run on if you use the "Run GoFSH" button.

### CODE REVIEW

**Review by ngfreiter — CHANGES_REQUESTED** [review]
This looks good. The only thing I've noticed is that the `Add Definition` button doesn't stretch across the entire sidebar in the same way the definitions do: 
image

I think it would make more sense to have that button be the same width as the definitions below.

**Comment by cmoesel** [comment]
This is very nice.  I really like it.  That said, I found a few issues in playing with it.  Some of which may be related to each other.  I've done screen captures for these -- so hopefully they come through.

1. A blank RHS is not noted as an error at first, but if you type in JSON and then delete it all (back to blank state), it is now an error.  I guess I'm not sure if that's good or bad.
FSH Online-20210324131428

2. If you add two (or more) untitled resources (for a total of three or more), then click on #1 and enter JSON, then click on #2 and enter JSON, it works. But then if you click on #3, the editor still shows #2 (no matter how many times you click).  The only way to get the blank editor is to click back on #2 again and then click on #3 again.
FSH Online-20210324132003

3. This is kind of silly, but if the first thing you do is delete the Untitled artifact (so there are no files on the RHS), then the editor is still active --- so if you type in a resource, as soon as the resource is valid JSON, the editor goes blank and the resource appears in the file tree.  So then you need to click on the resource in the file tree to continue editing.
FSH Online-20210324132623

4. I can make it crash!  Start fresh and type a FSH profile on the LHS.  Then run SUSHI.  Then "Add Definition" on the RHS.  Then run SUSHI again.   CRRRRRAAAAAASSSSHHHHHH!
FSH Online-20210324133106

**Review by cmoesel — CHANGES_REQUESTED** [review]
Oops.  Forgot to request changes when I commented on the bugs I found.

**Comment by jafeltra** [comment]
Thanks for finding those bugs @cmoesel. A quick summary of the fixes:

1. I agree that the inconsistency was weird and it felt odd to have a blank editor be invalid, so I just had an empty string (which is technically invalid JSON) be treated as an empty JSON object.
2. This was a bummer because I had tried something similar, noticed similar weirdness, and thought I fixed it, but apparently it only worked with 2 new definitions and I never tried with more. The root of this problem is that the CodeMirror component is using the `initialText` prop to rerender and clear out the editor. But when you add the group of definitions like you did, the `initialText` is always `null` and so switching to the other untitled editor doesn't clear the text that's present properly. Or at least that's what I think is happening. In order to get around that, I reset the `initialText` to be something other than `null` when you first start typing. This lets the text in the editor get managed by CodeMirror as you type, but it lets the `initialText` prop on the editor register a change when you swap editors. This is definitely a little odd, so let me know if you feel too iffy on this.
3. I'm not entirely sure why this happened, but I decided it was a little weird to have that empty list of files since we start the list out with a blank definition on load. So I decided to make sure we add back a blank definition if we have 0 definitions listed in the tree. So I think that resolves this bug.
4. The crash was happening because the "currently selected" definition index wasn't getting reset when we load in new definitions from SUSHI. Resetting that back to 0 selects the definition as expected and doesn't crash.

Bonus: I moved and renamed the "Share" button to make it more clear that we are sharing FSH, not JSON, like we talked about this morning.

**Review by cmoesel — CHANGES_REQUESTED** [review]
So this is looking good!  But I heard you like weird bugs.  So I have just one more for you. To reproduce:

* Refresh your page
* Add 3 more resources (for total of four)
* Edit them one at a time, top to bottom
* Go to 2nd item and create syntax error
* Delete 1st item

Result: Original 2nd item (now 1st item) will still be in red (good) but the original 3rd item (now 2nd item) will become red even though it has no errors (bad).  Merely clicking on it clears the error indicator.

FSH Online-20210324221050

**Comment by jafeltra** [comment]
Good bug finding @cmoesel! 6259a16 should fix it, along with one other tweak. The problem was that the definitions that have errors are kept track of through a separate array of indices, so that array wasn't being updated relative to the changing source array. That commit adjusts the indices to update any later occurring definitions. While looking at the function that handles deleting again, I also adjusted which definition is selected and displayed after deleting as well. Previously, any time a definition was deleted, the first one was reselected. Now it will only reselect the first one if you delete the one you are currently viewing and will shift to keep the same definition selected if you delete one that comes before it.

**Review by cmoesel — CHANGES_REQUESTED** [review]
It's working nice!  I found one behavior that feels a little odd to me, but it's not necessarily wrong (so if it's not easily fixed just say so).  Basically, if the 3rd (or 4th, etc) resource in a list is untitled, it will stay in its position as you edit until you have a parseable resourceType and id.  This makes sense.  But if you enter a blank id (`""`), it's name will stay "Untitled" but its position will hop up to the top of the list.  It's jarring to have the position change even though the name did not.
FSH Online-20210325124911

This is kind of an edge case, but I wonder if it will actually be aggravated when this is combined w/ auto-closing `""` since whenever you type an `id` it will always start with an empty string (and thus shoot to the top of the list until you type something into the string).

**Comment by jafeltra** [comment]
@cmoesel I believe this should be resolved now. I think that the filtering by id was changed whether the id was an empty string or just not defined. I resolved it by sorting all definitions that didn't have an `id` by the "Untitled" name, which is what they do when you first add them using the "Add Definition" button. I think the only potentially odd result of this is that they do get sorted alphabetically still, so you could end up with a list that looks like this: 

image

I think that is what I would expect, but want to make sure you agree.

I also discovered a bug where adding a bunch of blank definitions using the "Add Definition" button and sending them to GoFSH caused the app to crash. This was because `null` can be successfully parsed by `JSON.parse()`, so we didn't get the nice error message before sending definitions to GoFSH, but then GoFSH couldn't read `resourceType` from `null`, as expected. This now filters out any `null` or `undefined` definitions that we try to send to GoFSH.

**Review by cmoesel — APPROVED** [review]
Splendid!  Thanks for fixing all the silly probably-will-never-happen-in-the-real-world things for me!

**Review by ngfreiter — APPROVED** [review]
Chris took all the good breaking, so I'm unable to break it. Looks good to me!

**Pull request merged**
